#    Basic python skills


![THAIPASS 2018](https://indico.narit.or.th/event/81/logo-2988874644.png "Thaipass 2018 logo")


-----
### Using a jupyter notebook

Jupyter notebook is a browser based python package that allows for cell based coding.
Jupyter notebook can edit most text based files, but is designed to run `.ipynb` files, such as this one.
This can all be easliy done within the dashboard of the program.
The code uses a kernel as its computational engine, storing memory and processing tasks.
The kernal will store any functions, variables and previous code that has been ran.
The kernel can be reset by going into Kernal -> Restart & Clear Outputs.
If your code eeds to be stoped, for example if it is taking too long for a task, the kernel can be interupted by using the stop button ($\Box$) above the work area.
In order to run a cell with code in you simply have to shift+enter when interacting with the desired cell.

-----
### Python Basics

In this notebook we will give an overview of the basic python skills needed to create simple python scripts and begin to work towards basic data analysis. 
These skills will prepare you for the upcoming school.

The skills covered here are:

+ Basic Functions
    + Importing
    + Commenting
    + Printing outputs
    + Mathematic Functions
    + Variables
    
+ Data types
    + Integer, Floating point variables and Strings
    + Type statements
    + Conflicts and Combinations
    
+ Array/List
    + Contain many variables
    + Differences and conflicts
    + Nesting lists
    
+ Data structure
    + Indexing
    + Indenting
    + Objects
    
+ Boolean
    + True/False
    + If statements
    + Conditionals 
    
+ Simple Loops
    + For loops
    + While loops
    + Recursion
    
+ Input
    + External input
    + interactivity
    
-----
#### Debugging

One of the most important skills to familiarise yourself with is debugging your code.
When your code does not function it will generate an error message based on the issue it ran into.
Take the time to identify where you code is going wrong and attempt to fix it.
If the error message seems vague you may want to experiment with your code by changing variables and adding outputs to examine your code at each step.

-----
#### Tasks


At the end and throughout of this notebook you will find some basic tasks to test your skills with basic python. As python is an ever expanding platform many of the tasks can likely be done by external scripts, but in order to test yourself we ask that you use only the skills shown in this notebook.

### Importing modules and commenting

In [1]:
# This is a comment
# a = test
# The simple equation above is ignored due to being commented out

# Importing directly from the module name, we have shortened the numpy name to np
# np will be used as reference for numpy from here on in both the code and the comments
import numpy as np # Comments can be made after code and will function in the same way.

#Here we are importing the pyplot module form within the matplotlib module
#This can be done either way shown below
from matplotlib import pyplot as plt
import matplotlib.pyplot as plt

### Print statements
Print statements simply output a variable to be output onto the screen. 
Within a notebook it will output the string below the cell it is ran from.

In [2]:
# Below is a print statement that outputs the string attached
print('TEST')
print(1)   # An integer
print(1.5) # A float
# Print statment can contain calculations and functions:
print(type('Test'))

TEST
1
1.5
<class 'str'>


The final line of a cell will automatically be outputed

In [3]:
# The final line in a cell will be printed, if possible
'FINAL LINE 1'
'FINAL LINE 2'

'FINAL LINE 2'

### Basic python function
Simple and advanced mathematics can be performed by python. These use the standard mathematical opertors of `+`, `-`, `*`(mutiplication), `/`(division), `**`(exponents).

The code will follow standard mathematical rules, initially performing any math in parentheses, performing any indexing, any multiplication or division and finally any addition or subtraction.

In [4]:
# We can do simple mathematical functions, that can be built up to more complex functions
print(1+2)
print(5*2)
print(5**4)
print((3**3)**3)

3
10
625
19683


These mathematical functions can be made easier by using variables defined before hand.
to define a variable we simply equate values to a variable name, below we use `a` and `b`, but they can be any string of letters.
A variable name should be something that makes sense if writing a larger script.

In [5]:
# To define a variable simply equate it to something, variable names can be anything.
# Certain Pythonic commands are highlighted in green afterbeing typed (such as print)
# and should not be altered as a variable.
a=3
b=5
#These variables can be used to perform mathematical functions:
print('Variable calculations: ')
print(a+b)
print(a*b)
print(a**b)
print(a-b)

Variable calculations: 
8
15
243
-2


### Data types

Values within python can take the form of many types. 
Primarily we will be using the four basic types:
+ Integer values
+ Floating point values
+ Strings
+ Boolean

An integer (`int`) value are whole numbers that are either negative or positive.

A floating point (`float`) value has a decimal point dividing the integer and decimal portions. Floats can also be defined using scientific notation, eg `2.4e6` or `5.1E-9`.

A string value is a list of character enclosed in either quotation marks `'` or double quotation marks `"`.

Boolean vaues are returned as either `True` or `False`. These can be defined as variables, or generated as outputs such as `my_string.isnumeric()` which attempts to work out if a string (in this case `my_string`) is all numbers.

[Documentation: Boolean](https://www.pythonforbeginners.com/basics/boolean)

In [6]:
string = 'This is a string'
integer = 15
floatingpoint = 12.22
sci_notation = 1.5e10
print(string,integer,floatingpoint,sci_notation) # Here we are printing all the above variables
print(type(string),type(integer),type(floatingpoint),type(sci_notation))

This is a string 15 12.22 15000000000.0
<class 'str'> <class 'int'> <class 'float'> <class 'float'>


These data types can be interchanged, if the proper conditions are met to allow a transition. This is shown below.

In [7]:
print(int(sci_notation))
print(int(floatingpoint))
print(str(sci_notation))

15000000000
12
15000000000.0


As most of the work done in data analysis is numerical floats and integers are the core structure of your work.
Interactions between floats and integers must be taken into account in any calculation you perform.

In [8]:
print(integer+floatingpoint)
print(integer/2)
print(string.isnumeric())

27.22
7.5
False


### Arrays and Lists

Lists and arrays are used to contain many values within a single variable, but each have their own uses.

Lists are defined by placing values within a pair of square brackets (`[]`).
Arrays are a function of number python (`np`) and are created by using the `np.array()`) function on a list.

Lists can be "initialised" by creating a blank list like such: `list = []`. This allows for list manipulation, and is expanded on in the loops section.

[Documentation: Arrays](https://docs.scipy.org/doc/numpy/user/basics.creation.html)

[Documentation: Lists](https://www.pythonforbeginners.com/basics/python-list-manipulation)

In [9]:
list1 = [1.,2.,3.,4.,5.,6.,7.,8.]
list2 = [3.,4.,8.]

array1 = np.array([1.,2.,3.])
array2 = np.array([3.,4.,8.])

print(list1)
print(array2)

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
[3. 4. 8.]


Lists and arrays can be subtracted, multiplied and added together.

These interactions function differently between arrays and lists.

In [10]:
print(array1+array2)
print(list1+list2)
print(array1+list2)
print(array1*array2)

[ 4.  6. 11.]
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 3.0, 4.0, 8.0]
[ 4.  6. 11.]
[ 3.  8. 24.]


Lists and arrays are able to be directly interacted with mathematically.
Again these interactions differ between lists and arrays.

In [11]:
print(list1*3)
print(array1*3)

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
[3. 6. 9.]


Lists and arrays can themselves conatin lists and arrays. Nesting lists like this can allow for a large amount of information to be stored within a single variable name.
The next step is being able to extract that information.

In [12]:
nest1  = [list1,list2]

print(nest1)

[[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0], [3.0, 4.0, 8.0]]


### Data structure, formatting and syntax

##### Indexing
Python's list structure allows for variables to be indexed, calling specific values within a list.
For example you can call the first value in any list by indexing with 0, as python begins counting at 0. If you wanted to call the 5th value you would index by 4.
These indexes are placed after the list (or string) as such `list1[0]`.
By indexing with negative values you can index from the end of the list/string. 
Note that -0 and 0 are the same so reverse indexing begins from -1.

This indexing method can be expanded by using slicing. 
Slicing allows for a range of indexes to be obtained.
Slicing is performed by using a colon within a standard indexing method, for example `list1[2:5]`.
The slicing method can be best pictured as creating an upper and lower limit based on a *slice* between the values. An example of slicing points are shown here`:
 +---+---+---+---+---+---+
 | P | y | t | h | o | n |
 +---+---+---+---+---+---+
 0   1   2   3   4   5   6
-6  -5  -4  -3  -2  -1`





[Documentation: Data structure](https://docs.python.org/3/tutorial/datastructures.html)

In [13]:
print(list1[2])
print(list1[-2])
print(list1[-0])
print(list1[1:])
print(list1[1:4])
print(list1[3:-3])

3.0
7.0
1.0
[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
[2.0, 3.0, 4.0]
[4.0, 5.0]


##### Indenting
When a statement requires a specified section of code python asks only for a tabbed region, this is achieved by using the tab key or entering four spaces. 
This is made more obvious in the if statement and loops section.
A tabbed area denotes a section of code that is related to the statement before the tab, often ending with a `:`.
Tabbed sections of code can hold additional sections of tabbed code, alllowing for "stacking" loops and conditional statements.

##### Objects

Many objects in python can be diretly interacted with by basic python methods.

Some exmaple of list interactions, acting on the object `list`:

|Method|Interaction|
|:---:|:---|
|`list.append(x)`|Adds a value, *x*, at the end of a list
|`list.insert(i,x)`|Inserts a value, *x*, in a position, *i*
|`list.clear()`|Removes all items from a list
|`list.reverse()`|Reverses the order of a list

In [14]:
list_a = [1,2,3]
print(list_a)
list_a.append(2)
print(list_a)
list_a.insert(2,9)
print(list_a)
list_a.reverse()
print(list_a)
list_a.clear()
print(list_a)

[1, 2, 3]
[1, 2, 3, 2]
[1, 2, 9, 3, 2]
[2, 3, 9, 2, 1]
[]


Here we see some interactions with string objects, here denoted by `string`:

|Method|Interaction|
|:---:|:---|
|`string.capitalize()`|Capitalizes the first letter of the string|
|`string.upper()`|Capitalizes all letters in the string|
|`string.isnumeric()`|Checks if the string consists of only numerical values, providing a true/false response|
|`string.strip([char])`|Removes all leading and trailing characters that match the keyword `char`|
|`string.replace(old,new)`|Replaces all `old` characters with `new` characters|
|`string.find([char])`|Determines if the provided string, `str` is located within the string, providing an index if found and a -1 if no value found|


In [15]:
string = 'test string!'
print(string.upper())
print(string.isnumeric())
print(string.replace('s','x'))
print(string.strip('!'))

TEST STRING!
False
text xtring!
test string


##### Mini-task

Using the tools above to change the following strings into a useable numbers by removing the letters, and add them together

In [16]:
num1 = 'ppp145yy5ppppp' 
num2 = 'www1e2w' # This is in scientific notation
num3 = 'ttTTtT45tTWw' 



### If statements

If statements are logical conditional tests. These tests are based on the following conditional statements:

|Symbol|Conditonal|
|:----:|:----------|
|`==`|Equal to|
|`!=`|Not equal to|
|`>`|Greater than|
|`<`|Less then|
|`>=`|Greater than or equal to|
|`<=`|Less than or equal to|

These comparisons can be combined with `and`/`or` statements by both direct quoting of `and`/`or` or by combining conditionals such as `1<x<3`.

These statements provide a simple `True` or `False` output.



[Documentation: If statements](http://anh.cs.luc.edu/handsonPythonTutorial/ifstatements.html)

In [17]:
print(3<2)
  
x = 5
print(x == 5)
print(x == 6)
print(x != 6)
x = 6
print(6 == x)
print(6 != x)
print('hi' == 'h' + 'i')
print('HI' != 'hi')
print([1  ,  2] != [2,1])

False
True
False
True
True
False
True
True
True


If statements use the tabbing format to denote what is constrained by the statement.
The statement can be extended by use of `elif:`, allowing for an additional if statement that is only observed if the previous statement if found to be false. If statements can be stoppered by an `else:` statement, which will trigger if all `if` and `elif` statements are found to be false.

In [18]:
# Here you can alter the test value to see how it interacts with the loop below
test = 100
if test <=15:
    print('test passed')
elif 150 > test > 15:
    print('test failed')
else:
    print('far too high, over ten times too high')

test failed


### Simple loops

In order to perform large tasks we will need to repeat many steps over and over. This can be achieved through loops.

There are two core looping techniques: for and while.

A for loop is written in the following format:

`for i in x:`

Here we are interating over the values within `x`. This means that `x` must have a length of at least 1 in order for the loop to perform a task.

In [19]:
for i in list1:
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0


A loop can be placed within another loop (nesting loops) allowing a significant amount of actions to be performed with a small amount of code.

For example in the loops below we iterate over both list1 and list2, allowing for 24 calculations to be ran.

In [20]:
list3 = []
for i in list1:
    for j in list2:
        list3.append(i*j)
print(list3)

[3.0, 4.0, 8.0, 6.0, 8.0, 16.0, 9.0, 12.0, 24.0, 12.0, 16.0, 32.0, 15.0, 20.0, 40.0, 18.0, 24.0, 48.0, 21.0, 28.0, 56.0, 24.0, 32.0, 64.0]


A while loop uses the following format

`while x == 1:`

Here we are using the same conditionals as above in the boolean section. The loop will continue as long as the conditional provides a `True` value, allowing for the potential of infinite loops.

In [21]:
x=0
while x<3:
    print(x)
    x+=1

0
1
2


##### Mini-task

In the cell below you will find a string that contains a hidden code.

To decipher this code you must take every fifth letter in the string and print it.


In [22]:
code = ' GWVGHHPJKEWHFQLEUZVLFIRHOARFH QFIKTCCOWHMRREIGQFCSASBB PIOSIMTZGSEJKX SDYATGGRAHJPZIEJNZR YQTFSULRIEWQVVCYRUNRTSIAEDEBHTKLSN HDIKCBEQIOXLTZDJRIIETZCZ AUQC'



### Input

The input command allows an input to be called from an external source. This input can be equated to a variable and used within normal code.

This method of calling for an external input is not greatly used in data science, but is great for experimenting with your code.

In [23]:
weight = float(input("How many pounds does your suitcase weigh? "))
if weight >= 50:
    print("There is a \u0e3f250 charge for luggage that heavy.")
elif 50>weight>10:
    print("There is a \u0e3f50 charge for luggage that heavy.")
else:
    print("There is a no charge for luggage that light.")
print("Thank you for your business.")

How many pounds does your suitcase weigh? 50
There is a ฿250 charge for luggage that heavy.
Thank you for your business.



### Summary

##### Importing
We begin with importing modules from the inbuilt python install. 
We can import directly form the name of the module, or call a module from within another. 
These modules can be renamed in order to reduce retyping long module names.

##### Commenting
Lines that begin with a `#` are comments, these are ignored by the script and are used to take notes and explain the functionality of the code.
Comments can also be used to cause sections of your code to be ignored when the cell is ran.

##### Print statements
Print statements output a string onto the screen. Within a notebook it will output the string below the cell it is ran from.

##### Basic python function
Simple and advanced mathematics can be performed by python. These use the standard mathematical opertors of `+`, `-`, `*`(mutiplication), `/`(division), `**`(indexing).

The code will follow standard mathematical rules, initially performing any math in parentheses, performing any indexing, any multiplication or division and finally any addition or subtraction.

Values are often placed into variables. These variable will maintain the memory of any actions aligned with them, can can be called in future calculations.

##### Data classes/types
The data that you will create can come in many forms. The core three types are Integer, Float and String.

An integer (`int` in `type()` outputs) value consists of only a whole number, with no decimal point. They can be positive or negative.

Float (`float` in `type()` outputs) values are numbers with a decimal point in them, these are the values you will likely use most for this workshop.

Strings (`str` in `type()` outputs) are simply unicode characters in a list, this can be used to create words.

The data types can be identified by using the `type(x)` command, where x is your variable/value.

The different types of data interact in specific ways. 

##### Arrays & Lists
Arrays and lists can be used to collect data. Arrays are created using number python and lists are inbuilt to python.
In order to create an array the `numpy.array()` command must be used.
Arrays and lists may seem to be identical but they interact with each other and basic mathematical funtions differently.

##### Data structure
Lists and arrays can be used to call specific values called indexing. This can be perfomed by placing a number in square brackets after a list. Using a colon we can slice the list.

Some python code requires indenting to identify where that function is working over. These functions include loops and if statements.

Many python values can be interacted with using objects, there are simple objects that allow for quick coding and more complex objects that can skip large blocks of manual code.

##### Boolean satements
A type of class a variable can be is a boolean value (`bool` in `type()` outputs).
Boolean values can be used to define if statement conditions, by either calling a True or False value or using 

##### Simple loops
There are two simple looping techniques: for statements and while statements.
For statements produce a loop based on predetermined inputs, such as 1 to 10.
While loops will continue to loop as long as the boolean operator is met.

##### Input
Python can ask the user to input their own values, which can be stored in a variable, allowin for direct user interaction without having to open the code to alter the output.



## Tasks

Here we will give you some simple coding tasks that will test the basic skills in python you have learned above.

Your first task is to use the random numbers generated below to create a list of simple statistical values, the numbers are stored in the list as strings so will have to be reformatted:
+ Calculate the mean
+ Calculate the median
+ Calculate the standard deviation
+ Calculate the variance

<p style="text-align: center;">The equation for standard deviation ($\sigma$) is:</p>
<p style="text-align: center;">$ \sigma = \sqrt{\frac{\sum (x-\bar{x})^{2}}{N}} $</p>
<p style="text-align: center;"> Where $x$ is a value, $\bar{x}$ is the average, $N$ is the number of values </p>
<p style="text-align: center;"> Variance is simply: </p>
<p style="text-align: center;"> $Var(x) = \sigma^{2}$ </p>

Your second task is to write a script that will give information about a value generated by input.
The code should identify the following things about the input value:
+ is the value odd or even?
+ is the value prime?
+ is the value a square factor?
+ Is the value on the Fibonacci sequence?

In [24]:
# These are the datasets used in your first task.
rnd_data = [np.random.randint(1000) for i in range(10000)]
nrm_data = [np.random.normal() for i in range(10000)]